dependencies {
    api(libs.snakeyaml)
    api(libs.configurate.yaml)
    api(libs.configurate.extra.kotlin)
//    api(libs.cloud.kotlin.coroutines)
    api(libs.adventure.api)
    api(libs.adventure.text.minimessage)
    api(libs.adventure.text.serializer.gson)
    api(libs.mysql.connector)
    api(libs.jedis)
    api(libs.reflections)
    api(libs.hikari)
    api(libs.gson)
    api(libs.kotlin.reflect)
    api(libs.kotlinx.coroutines)
    api(libs.java.websocket)
    api(libs.mariadb)
    api(libs.exposed.core)
    api(libs.exposed.jdbc)
//    api(libs.exposed.r2dbc)
    api(libs.exposed.dao)
    api(libs.exposed.kotlin.datetime)
    api(libs.kaml)

    compileOnlyApi(libs.guava)
    compileOnlyApi(libs.netty.all)
}
